Acronym.Web/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace Acronym.Web.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

Acronym.Web/Models/AcronymViewModel.cs
namespace Acronym.Web.Models
{
    public class AcronymViewModel
    {
        public string Id { get; set; }
        public string AcronymText { get; set; }
    }
}

Acronym.Web/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Acronym.Web.Areas.HelpPage.Models;

namespace Acronym.Web.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

Acronym.Web/Controllers/AcronymController.cs
using System;
using System.Collections.Generic;
using System.Web.Http;
using Acronym.Domain;
using Acronym.Web.Models;
using AutoMapper;

namespace Acronym.Web.Controllers
{
    public class AcronymController : EntityController<Data.Entities.Acronym>
    {
        // GET api/Acronym
        public IEnumerable<AcronymViewModel> Get()
        {
            return Mapper.Map<IEnumerable<AcronymViewModel>>(repository.All());
        }

        // GET api/Acronym/5
        public AcronymViewModel Get(string id)
        {
            return Mapper.Map<AcronymViewModel>(repository.Find(id));
        }

        // POST api/Acronym
        public void Post([FromBody]CreateAcronym value)
        {
            var handler = new AcronymHandler(repository);
            handler.Handle(value);
        }

        // PUT api/Acronym/5
        public void Put(string id, [FromBody]SubmitAcronymResponse value)
        {
            var handler = new AcronymHandler(repository);
            handler.Handle(value);
        }

        // DELETE api/Acronym/5
        public void Delete(string id)
        {
        }
    }
}

Acronym.Web/Controllers/EntityController.cs
using System.Web.Http;
using System.Web.Http.Controllers;
using Acronym.Data;

namespace Acronym.Web.Controllers
{
    public class EntityController<TEntity> : ApiController where TEntity : IEntity
    {
        protected IRepository<TEntity> repository;
 
        protected override void Initialize(HttpControllerContext controllerContext)
        {
            base.Initialize(controllerContext);
            var context = new DataContext();
            repository = context.GetRepository<TEntity>();
        }
    }
}

Acronym.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Acronym.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Acronym.Web/Views/Home/Index.cshtml
<div ng-app='acronym'>
    <div ng-view></div>
</div>

@*<div id="add-container">
    <form id="add-form">
        <input type="text" id="text" />
        <button id="add">Add!</button>
    </form>
</div>

<div id="test"></div>*@

@section scripts {
    @*<script type="text/javascript">
        $(function () {

            function getAcronyms() {
                $.get('/api/Acronym', function (data) {
                    console.log(data);

                    var node = $("#test");
                    node.empty();

                    for (var i = 0; i < data.length; i++) {
                        var acronym = data[i],
                            id = acronym.id,
                            text = acronym.acronymText;

                        node.append($("<div>").text('id: ' + id + ', text: ' + text));
                    }
                });
            }

            $("#add-form").submit(function () {
                $.ajax({
                    url: '/api/Acronym',
                    type: 'POST',
                    data: { acronym: $("#text").val() },
                    success: function() {
                        getAcronyms();
                    }
                });

                $("#text").val('');
                return false;
            });

            getAcronyms();
        })
    </script>*@
}

Acronym.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/angular-app")
    @RenderSection("scripts", required: false)
</body>
</html>